<?php
/**
 * @var array $user
 */

?>

<h1>NEW USER</h1>
<form action="/users" method="post">
    <div>
        <label>
            Nickname
            <select>
                <option value="">-- Выберите тип подписки --</option>
                <option value="true" selected>true</option>
                <option value="false">false</option>
            </select>
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email'])?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Submit">
</form>